# Generated by Django 4.0.3 on 2022-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_record_kitob_alter_record_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='qaytardi',
            field=models.CharField(blank=True, default="Yo'q", max_length=5),
        ),
        migrations.AddField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
